name: Run build
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-22.04.3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Commit and push
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update build
          commit_author: fabrinucci
